[project]
name = "llm-clients"
version = "0.1.0"
description = "Utility library to run local LLMs"
readme = "README.md"
authors = [
    { name = 'Mehtab "Shahan" Iqbal', email = "mehtabi@clemson.edu" }
]
requires-python = ">=3.11, <3.13"
dependencies = [
    "structlog>=25.5.0",
    "openai>=2.31.0",
    "dotenv>=0.9.9",
    "tiktoken>=0.12.0",
]

[project.optional-dependencies]
local = [
    "accelerate>=1.13.0",
    "transformers>=5.5.4",
    "torch>=2.5.0",
    "torchvision>=0.20.0",  
    "torchaudio>=2.5.0",
    "bitsandbytes>=0.42.0",
]

[[tool.uv.index]]
name = "pytorch-cu121"
url = "https://download.pytorch.org/whl/cu121"
explicit = true

[tool.uv.sources]
torch = [{ index = "pytorch-cu121" }]
torchvision = [{ index = "pytorch-cu121" }]
torchaudio = [{ index = "pytorch-cu121" }]

[build-system]
requires = ["uv_build>=0.11.2,<0.12.0"]
build-backend = "uv_build"
